[build]
  publish = "public"
  command = "npm run lint && npm run build && npm run postBuild"

# Build
[[plugins]]
  package = "@helloample/netlify-plugin-replace"

[[plugins]]
  package = "netlify-plugin-image-optim"

# Analyze
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-a11y"

[[plugins]]
  package = "netlify-plugin-checklinks"

# Notify
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
